add server id config variable and make home test optional in restart_connotea
darcs-hash:20080515060150-41d90-5205d37f246dd496f40a233c8240f84576e97e36.gz

diff --git a/deploy/restart_connotea b/deploy/restart_connotea
--- a/deploy/restart_connotea
+++ b/deploy/restart_connotea
@@ -12,11 +12,13 @@ if ! ps axf | grep -v grep | grep -q httpd; then
   echo "ERROR: Process list does not show Apache!"
   exit 10
 fi
-ip=`ifconfig eth0 | perl -ne '/inet addr:(\S+)/ && print "$1\n"'`
-curl -s -H "Host: $HOST" "http://$ip/" > /tmp/web
-if ! grep -q $HOMETEST /tmp/web; then
-  echo "ERROR: Web request for $HOST does not yield proper page!"
-  exit 11
+if [ "$HOMETEST" ]; then
+  ip=`ifconfig eth0 | perl -ne '/inet addr:(\S+)/ && print "$1\n"'`
+  curl -s -H "Host: $HOST" "http://$ip/" > /tmp/web
+  if ! grep -q $HOMETEST /tmp/web; then
+    echo "ERROR: Web request for $HOST does not yield proper page!"
+    exit 11
+  fi
+  rm -f /tmp/web
 fi
-rm -f /tmp/web
 echo "Restart completed OK."
